name: Docker Image CI

on:

  push:
    branches: [ "main" ]

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      # Enable caching for docker image layers
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          tags: mlops-challenge:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
