name: Lint Dockerfile

on: 

  push:
    branches: [ "main" ]
    
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.5.0

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error
